server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: 12345
    pool-size: 100  #
  jpa:
    driver: com.mysql.cj.jdbc.Driver
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect  #
      show-sql: true  #
      ddl-auto: update

config:
  webinterface: /admin
  agent: SearchEngineBot
  sites:
#    - url: https://www.rastr89.ru/
#      name: РАСТР
#    - url: https://artline89.ru/
#      name: АртЛайн
#    - url: http://www.playback.ru/
#      name: PlayBack
    - url: https://volochek.life/
      name: Волочёк
#    - url: http://radiomv.ru/
#      name: РадиоМВ
#    - url: https://ipfran.ru/
#      name: ИПФан
    - url: https://dimonvideo.ru/
      name: ДимонВидео
#    - url: https://nikoartgallery.com
#      name: Галерея
    - url: https://et-cetera.ru/mobile/
      name: ЭлЦентра. Мобильная версия
#    - url:  https://www.lutherancathedral.ru
#      name: Кафедральный собор
#    - url: https://dombulgakova.ru/
#      name: Дом Булгакова
#    - url: https://www.svetlovka.ru/
#      name: Светловка